language: go
go:
- 1.7.3
- tip
env:
  global:
  - GO_FOR_RELEASE=1.7.3
  - IMAGE_NAME=maddevsio/sm-http-agent
services:
  - docker
script:
  - go test -v .
  - go build -v
  - curl https://raw.githubusercontent.com/maddevsio/travis-push-to-docker/master/sm-push.sh | bash
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 sm-docker-key && 
    ssh -o StrictHostKeyChecking=no -i ./sm-docker-key sm-docker@sm.maddevs.io "pull $IMAGE_NAME:v.$TRAVIS_BUILD_NUMBER" &&
    ssh -o StrictHostKeyChecking=no -i ./sm-docker-key sm-docker@sm.maddevs.io "rm -f sm-http-agent" || true &&
    ssh -o StrictHostKeyChecking=no -i ./sm-docker-key sm-docker@sm.maddevs.io "run -d --restart=always --name=sm-http-agent -p 127.0.0.1:9090:8090 -e PORT=8090 -e DASHBOARD_URL=http://sm.maddevs.io/dashboard/v1/register -e TARGET_HOST=github.com:443 $IMAGE_NAME:v.$TRAVIS_BUILD_NUMBER"
  on:
    go: '1.7.3'
